# Generated by Django 5.2.4 on 2026-01-03 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_location_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='dimensions_unit',
            field=models.CharField(blank=True, choices=[('in', 'Inches'), ('cm', 'Centimeters'), ('ft', 'Feet'), ('m', 'Meters')], help_text='Unit of measurement for dimensions', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='height',
            field=models.FloatField(blank=True, help_text='Height dimension', null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='length',
            field=models.FloatField(blank=True, help_text='Length dimension', null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='width',
            field=models.FloatField(blank=True, help_text='Width dimension', null=True),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('dimensions_unit__isnull', True), ('height__isnull', True), ('length__isnull', True), ('width__isnull', True)), models.Q(('dimensions_unit__isnull', False), ('height__isnull', False), ('length__isnull', False), ('width__isnull', False)), _connector='OR'), name='unit_dimensions_all_or_nothing'),
        ),
    ]
