# Generated by Django 5.2.4 on 2026-01-26 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_unit_dimensions_unit_alter_unit_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmsuser',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='If True, user will be required to change password on next login.'),
        ),
    ]
