# Generated by Django 5.2.4 on 2026-02-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_wmsuser_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.FloatField(blank=True, help_text='Amount of this item', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='quantity_unit',
            field=models.CharField(blank=True, choices=[('Count', [('count', 'Count')]), ('Mass', [('lb', 'Pounds'), ('kg', 'Kilograms'), ('g', 'Grams'), ('mg', 'Milligrams'), ('oz', 'Ounces')]), ('Volume', [('mL', 'Milliliters'), ('gal', 'Gallons'), ('L', 'Liters'), ('fl_oz', 'Fluid Ounces')]), ('Length', [('mm', 'Millimeters'), ('ft', 'Feet'), ('m', 'Meters'), ('in', 'Inches'), ('cm', 'Centimeters')])], default='', help_text='Unit of measurement for quantity', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('quantity__isnull', True), ('quantity_unit', '')), models.Q(('quantity__isnull', False), models.Q(('quantity_unit', ''), _negated=True)), _connector='OR'), name='item_quantity_all_or_nothing'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__isnull', True), ('quantity__gte', 0), _connector='OR'), name='item_quantity_non_negative'),
        ),
    ]
