# Generated by Django 5.2.4 on 2026-02-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_quantity_item_quantity_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantity_unit',
            field=models.CharField(blank=True, choices=[('Count', [('count', 'Count')]), ('Mass', [('lb', 'Pounds'), ('mg', 'Milligrams'), ('oz', 'Ounces'), ('kg', 'Kilograms'), ('g', 'Grams')]), ('Volume', [('mL', 'Milliliters'), ('L', 'Liters'), ('fl_oz', 'Fluid Ounces'), ('gal', 'Gallons')]), ('Length', [('ft', 'Feet'), ('m', 'Meters'), ('mm', 'Millimeters'), ('in', 'Inches'), ('cm', 'Centimeters')])], default='', help_text='Unit of measurement for quantity', max_length=10),
        ),
    ]
