# Generated by Django 5.2.4 on 2026-02-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_item_quantity_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity_unit',
            field=models.CharField(blank=True, choices=[('Count', [('count', 'Count')]), ('Mass', [('mg', 'Milligrams'), ('oz', 'Ounces'), ('lb', 'Pounds'), ('g', 'Grams'), ('kg', 'Kilograms')]), ('Volume', [('L', 'Liters'), ('fl_oz', 'Fluid Ounces'), ('mL', 'Milliliters'), ('gal', 'Gallons')]), ('Length', [('cm', 'Centimeters'), ('m', 'Meters'), ('ft', 'Feet'), ('mm', 'Millimeters'), ('in', 'Inches')])], default='', help_text='Unit of measurement for quantity', max_length=10),
        ),
    ]
