# Generated by Django 5.2.4 on 2026-02-12 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_item_description_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount of this item', max_digits=10, null=True),
        ),
    ]
