# Generated by Django 5.2.4 on 2026-02-26 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_item_quantity_to_decimal_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantity_unit',
            field=models.CharField(blank=True, choices=[('Count', [('count', 'Count')]), ('Length', [('cm', 'Centimeters'), ('ft', 'Feet'), ('in', 'Inches'), ('m', 'Meters'), ('mm', 'Millimeters')]), ('Mass', [('g', 'Grams'), ('kg', 'Kilograms'), ('lb', 'Pounds'), ('mg', 'Milligrams'), ('oz', 'Ounces')]), ('Volume', [('L', 'Liters'), ('fl_oz', 'Fluid Ounces'), ('gal', 'Gallons'), ('mL', 'Milliliters')])], default='', help_text='Unit of measurement for quantity', max_length=10),
        ),
    ]
