# Generated by Django 5.2.4 on 2026-02-26 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_item_quantity_unit_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmsuser',
            name='has_completed_onboarding',
            field=models.BooleanField(default=False, help_text='If True, user has completed the onboarding wizard.'),
        ),
    ]
