# Generated by Django 5.2.4 on 2026-02-26 21:22

from django.db import migrations


def set_existing_users_onboarded(apps, schema_editor):
    """Mark all existing users as having completed onboarding."""
    WMSUser = apps.get_model("core", "WMSUser")
    WMSUser.objects.update(has_completed_onboarding=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_wmsuser_has_completed_onboarding'),
    ]

    operations = [
        migrations.RunPython(set_existing_users_onboarded, migrations.RunPython.noop),
    ]
