# Generated by Django 5.2.4 on 2026-03-22 00:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_set_existing_users_onboarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='shared_users',
            field=models.ManyToManyField(blank=True, related_name='shared_locations', through='core.LocationSharedAccess', to=settings.AUTH_USER_MODEL),
        ),
    ]
