# Generated by Django 5.2.4 on 2026-03-23 21:44

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_location_shared_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationsharedaccess',
            name='permission',
            field=models.CharField(choices=[('read', 'read'), ('write', 'write'), ('write_all', 'write_all')], default=core.models.Permission['READ'], max_length=50),
        ),
        migrations.AlterField(
            model_name='unitsharedaccess',
            name='permission',
            field=models.CharField(choices=[('read', 'read'), ('write', 'write'), ('write_all', 'write_all')], default=core.models.Permission['READ'], max_length=50),
        ),
        migrations.AddConstraint(
            model_name='locationsharedaccess',
            constraint=models.CheckConstraint(condition=models.Q(('permission__in', ['read', 'write', 'write_all'])), name='locationsharedaccess_valid_permission'),
        ),
        migrations.AddConstraint(
            model_name='unitsharedaccess',
            constraint=models.CheckConstraint(condition=models.Q(('permission__in', ['read', 'write', 'write_all'])), name='unitsharedaccess_valid_permission'),
        ),
    ]
